name: robostream

description: "RoboStream - Aplicación de control y monitoreo robótico con interfaz Flutter"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_staggered_animations: ^1.1.1

  simple_animations: ^5.0.2

  flutter_tilt: ^3.0.1

  flutter_bloc: ^9.1.1

  equatable: ^2.0.5

  dartssh2: ^2.9.2

  web_socket_channel: ^2.4.0
  
  http: ^1.2.1

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # Paquete para generar iconos automáticamente
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/Images/

  # Usar solo las dos fuentes Roboto que tienes en assets
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700

# Configuración para los iconos de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/Images/ROBOSTREAM_FINAL_ICON.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: false # Mantener transparencia en iOS
  adaptive_icon_background: "#1F2937" # Fondo más oscuro para mayor contraste
  adaptive_icon_foreground: "lib/assets/Images/ROBOSTREAM_FINAL_ICON.png" # Icono frontal para Android adaptativo
  adaptive_icon_padding: 0 # Sin padding para icono más grande
  web:
    generate: true
    image_path: "lib/assets/Images/ROBOSTREAM_FINAL_ICON.png"
    background_color: "#1F2937"
    theme_color: "#6366F1"
  windows:
    generate: true
    image_path: "lib/assets/Images/ROBOSTREAM_FINAL_ICON.png"
    icon_size: 256 # Máximo permitido para Windows
  macos:
    generate: true
    image_path: "lib/assets/Images/ROBOSTREAM_FINAL_ICON.png"
    icon_size: 1024 # Aumentado a 1024 para macOS (máximo soporte)